# Generated by Django 3.1.5 on 2021-01-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210119_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='modelo',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='precio',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Precio'),
        ),
    ]
